### ISSUE TITLE
Discussion 

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/fsharp-injections-demo#1]
Based on

> But I've been stopped by weird behavior 

I think the ruby generator wasn't explained very well because it addresses a large part of exactly what you're bringing up.

It detects (static analysis) and produces warnings that explain why certain patterns won't behave how you expect. For example, if you have a pattern that uses a quantifier on a capture group and then you try to tag the capture group, the library catches that and tells you only the first match is going to be highlighted and it explains how to fix it. Another example is if you have a pattern that accidentally matches  a zero length string, it catches that, tells you what going on, what pattern is the issue, and allows you to override the warning if you decide "yes I actually meant to do that". 

The yaml version isn't even close to addressing the very problems being complained about, but the ruby library is.

> As I mentioned there are a few tricks to do it much more succinctly than either JSON or Ruby with plain YAML

I think there's a misunderstanding here. There's plenty of decent arguments against using the ruby version, and I love yaml (it's my favorite serialization format by far). But, it is computationally provable that the ruby format can be more succinct than any of the static format methods. It would essentially need to be incompressible (a binary file with maxium entropy) for a static file to be less succinct. Here's [a demo showing how much more succinct this F# injection could be](https://github.com/jeff-hykin/fsharp-injections-demo/blob/succinct/main.rb) (there's only 2 files in that branch and one of them is the tmLanguage itself). This is partly because library was made to compress grammars and partly because Ruby has some nice syntax. Having the extra power of yaml-variables helps, but don't forget the regex is still being double -- and sometimes triple -- escaped. More importantly, the yaml version must explicitly mention capture group numbers, and it can't avoid duplication of tags because at minimum the variables representing the tag names have to be copied and pasted every time the pattern is used in multiple places. The ruby code maps 1-to-1 to the tmLanguage format, but at a much higher compression level because it automates repetition; for all practical purposes it can always be more succinct. 

Just look at the example with the F# injection, there is tons of code duplication. I left the duplication in the master branch to make the 1-to-1 mapping more clear. Despite the example syntax being very small, the ruby version can be half the size with better readability for people who don't have 15 years of experience with regex.

**Comment by texastoland** [comment]
> it addresses a large part of exactly what you're bringing up.

I really respect your work. For me it doesn't. In no way does that diminish your project. But I'll explain my perspective since you shared yours.

> It detects (static analysis) and produces warnings

I agree that's useful. Better as a linter though. Of course it's simpler to implement as a Ruby DSL. But that also introduces the complexities and verbosity of an entire PL as opposed to a constrained DSL like [Iro](https://eeyo.io/iro/) or the default YAML config. Regardless nothing short of a really clever transpiler could resolve limitations like tokenizing `func arg` identically as `func\narg`.

> Another example is if you have a pattern that accidentally matches a zero length string

Did I mention I hate TextMate grammars? That specific case effectively prevents exhaustive parsing. What's worse is no one including Microsoft (or you or I) has documented it.

> The yaml version isn't even close to addressing the very problems being complained about

Linting would require an extension; duplication is already partially addressed. You alluded that YAML provides the ability to duplicate or even merge blocks although you can't modify existing keys. On the other hand TextMate itself provides the ability to embed scope names from match groups acting like CSS for grammars:

```yaml
scopeName: inline.template-fsharp-highlight
injectionSelector: "L:- comment - (string - meta.embedded)"
patterns:
  - include: "#template"
repository:
  template:
    contentName: string.quoted.triple.fsharp.template.${1:/downcase}
    begin: |
      (?xi)     # Ignore whitespace and case
      (?<=      # After valid lang ($1 above) with any prefix
        (html|svg|sql)
      )
      \ *       # Arbitrary spaces
      (?=\$""") # Before interpolated string
    end: ^      # Before next line text
    patterns:
      - include: "#template_string"
  template_string:
    contentName: meta.embedded.block
    begin: \$"""
    end: |-
      """
    beginCaptures:
      0: { name: punctuation.definition.string.begin.fsharp }
    endCaptures:
      0: { name: punctuation.definition.string.end.fsharp }
```

Now it's trivial to embed HTML modularly for example:

```yaml
scopeName: inline.template-fsharp-highlight.html
injectionSelector: "L:string.quoted.triple.fsharp.template.html meta.embedded.block"
patterns: { include: text.html.derivative }
```

> the ruby format can be more succinct than any of the static format methods.

Compared to YAML yes; more than Iro no.

> Here's a demo showing how much more succinct this F# injection could be

There's subjectively more syntactic clutter and mental overhead than my version.

> don't forget the regex is still being double -- and sometimes triple -- escaped.

Note: only regex escaping is necessary thanks to YAML block scalars.

> Just look at the example with the F# injection, there is tons of code duplication.

I'm not the original author of that version. I don't disagree tmLanguage in any format is fundamentally flawed. For my narrow use case a Ruby dependency would make it too abstruse though. I'd happily use Iro in the future. But in general I find the existing Tree-sitter extension the happiest compromise rather than supporting a technology [I want to be deprecated](https://twitter.com/texastoland/status/1439272401292824581?s=20) (3 freaking years since Atom did it).

> better readability for people who don't have 15 years of experience with regex.

You can't completely abstract regex either and it clearly isn't the hard part writing TextMate grammars. I'm not trying to be contentious. I was impressed when I saw your Bash grammar 1 year ago. The Reason language originally did the same thing except in OCaml. I just prefer a different level of abstraction.
